/*
 * Copyright (C) 2017 Solenoid Augment Technologies Limited.
 * All rights reserved.
 */

// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.29 at 02:53:44 PM IST 
//

package com.solenoid.connector.sd.beans;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for CourierType.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name="CourierType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="NotSet"/&gt;
 *     &lt;enumeration value="BluePackage"/&gt;
 *     &lt;enumeration value="USPS"/&gt;
 *     &lt;enumeration value="UPS"/&gt;
 *     &lt;enumeration value="UPSMI"/&gt;
 *     &lt;enumeration value="FedEx"/&gt;
 *     &lt;enumeration value="DHL"/&gt;
 *     &lt;enumeration value="DHLGlobalMail"/&gt;
 *     &lt;enumeration value="Fastway"/&gt;
 *     &lt;enumeration value="UPSMailInnovations"/&gt;
 *     &lt;enumeration value="Lasership"/&gt;
 *     &lt;enumeration value="RoyalMail"/&gt;
 *     &lt;enumeration value="FedExSmartPost"/&gt;
 *     &lt;enumeration value="OSM"/&gt;
 *     &lt;enumeration value="OnTrac"/&gt;
 *     &lt;enumeration value="Streamlite"/&gt;
 *     &lt;enumeration value="Newgistics"/&gt;
 *     &lt;enumeration value="CanadaPost"/&gt;
 *     &lt;enumeration value="GLS"/&gt;
 *     &lt;enumeration value="GO"/&gt;
 *     &lt;enumeration value="HermesLogistikGruppe"/&gt;
 *     &lt;enumeration value="Parcelforce"/&gt;
 *     &lt;enumeration value="TNT"/&gt;
 *     &lt;enumeration value="Target"/&gt;
 *     &lt;enumeration value="SagawaExpress"/&gt;
 *     &lt;enumeration value="NipponExpress"/&gt;
 *     &lt;enumeration value="YamatoTransport"/&gt;
 *     &lt;enumeration value="Other"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "CourierType")
@XmlEnum
public enum CourierType {

	@XmlEnumValue("NotSet")
	NOT_SET("NotSet"), @XmlEnumValue("BluePackage")
	BLUE_PACKAGE("BluePackage"), USPS("USPS"), UPS("UPS"), UPSMI("UPSMI"), @XmlEnumValue("FedEx")
	FED_EX("FedEx"), DHL("DHL"), @XmlEnumValue("DHLGlobalMail")
	DHL_GLOBAL_MAIL("DHLGlobalMail"), @XmlEnumValue("Fastway")
	FASTWAY("Fastway"), @XmlEnumValue("UPSMailInnovations")
	UPS_MAIL_INNOVATIONS("UPSMailInnovations"), @XmlEnumValue("Lasership")
	LASERSHIP("Lasership"), @XmlEnumValue("RoyalMail")
	ROYAL_MAIL("RoyalMail"), @XmlEnumValue("FedExSmartPost")
	FED_EX_SMART_POST("FedExSmartPost"), OSM("OSM"), @XmlEnumValue("OnTrac")
	ON_TRAC("OnTrac"), @XmlEnumValue("Streamlite")
	STREAMLITE("Streamlite"), @XmlEnumValue("Newgistics")
	NEWGISTICS("Newgistics"), @XmlEnumValue("CanadaPost")
	CANADA_POST("CanadaPost"), GLS("GLS"), GO("GO"), @XmlEnumValue("HermesLogistikGruppe")
	HERMES_LOGISTIK_GRUPPE("HermesLogistikGruppe"), @XmlEnumValue("Parcelforce")
	PARCELFORCE("Parcelforce"), TNT("TNT"), @XmlEnumValue("Target")
	TARGET("Target"), @XmlEnumValue("SagawaExpress")
	SAGAWA_EXPRESS("SagawaExpress"), @XmlEnumValue("NipponExpress")
	NIPPON_EXPRESS("NipponExpress"), @XmlEnumValue("YamatoTransport")
	YAMATO_TRANSPORT("YamatoTransport"), @XmlEnumValue("Other")
	OTHER("Other");
	private final String value;

	CourierType(String v) {
		value = v;
	}

	public String value() {
		return value;
	}

	public static CourierType fromValue(String v) {
		for (CourierType c : CourierType.values()) {
			if (c.value.equals(v)) {
				return c;
			}
		}
		throw new IllegalArgumentException(v);
	}

}
