/*
 * Copyright (C) 2017 Solenoid Augment Technologies Limited.
 * All rights reserved.
 */

// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.29 at 02:53:44 PM IST 
//

package com.solenoid.connector.sd.beans;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the sd.soap.beans package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	/**
	 * Create a new ObjectFactory that can be used to create new instances of
	 * schema derived classes for package: sd.soap.beans
	 * 
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link UploadStock }
	 * 
	 */
	public UploadStock createUploadStock() {
		return new UploadStock();
	}

	/**
	 * Create an instance of {@link UploadStockResponse }
	 * 
	 */
	public UploadStockResponse createUploadStockResponse() {
		return new UploadStockResponse();
	}

	/**
	 * Create an instance of {@link UploadStockResponse2 }
	 * 
	 */
	public UploadStockResponse2 createUploadStockResponse2() {
		return new UploadStockResponse2();
	}

	/**
	 * Create an instance of {@link UploadSupplierStock }
	 * 
	 */
	public UploadSupplierStock createUploadSupplierStock() {
		return new UploadSupplierStock();
	}

	/**
	 * Create an instance of {@link UploadSupplierStockResponse }
	 * 
	 */
	public UploadSupplierStockResponse createUploadSupplierStockResponse() {
		return new UploadSupplierStockResponse();
	}

	/**
	 * Create an instance of {@link UploadSupplierStockToMarketplaces }
	 * 
	 */
	public UploadSupplierStockToMarketplaces createUploadSupplierStockToMarketplaces() {
		return new UploadSupplierStockToMarketplaces();
	}

	/**
	 * Create an instance of {@link ArrayOfString }
	 * 
	 */
	public ArrayOfString createArrayOfString() {
		return new ArrayOfString();
	}

	/**
	 * Create an instance of {@link UploadSupplierStockToMarketplacesResponse }
	 * 
	 */
	public UploadSupplierStockToMarketplacesResponse createUploadSupplierStockToMarketplacesResponse() {
		return new UploadSupplierStockToMarketplacesResponse();
	}

	/**
	 * Create an instance of {@link BulkUploadStock }
	 * 
	 */
	public BulkUploadStock createBulkUploadStock() {
		return new BulkUploadStock();
	}

	/**
	 * Create an instance of {@link BulkUploadStockResponse }
	 * 
	 */
	public BulkUploadStockResponse createBulkUploadStockResponse() {
		return new BulkUploadStockResponse();
	}

	/**
	 * Create an instance of {@link BulkUploadStockResponse2 }
	 * 
	 */
	public BulkUploadStockResponse2 createBulkUploadStockResponse2() {
		return new BulkUploadStockResponse2();
	}

	/**
	 * Create an instance of {@link BulkUploadStockUsingId }
	 * 
	 */
	public BulkUploadStockUsingId createBulkUploadStockUsingId() {
		return new BulkUploadStockUsingId();
	}

	/**
	 * Create an instance of {@link BulkUploadStockUsingIdResponse }
	 * 
	 */
	public BulkUploadStockUsingIdResponse createBulkUploadStockUsingIdResponse() {
		return new BulkUploadStockUsingIdResponse();
	}

	/**
	 * Create an instance of {@link BulkUploadCheck }
	 * 
	 */
	public BulkUploadCheck createBulkUploadCheck() {
		return new BulkUploadCheck();
	}

	/**
	 * Create an instance of {@link BulkUploadCheckResponse }
	 * 
	 */
	public BulkUploadCheckResponse createBulkUploadCheckResponse() {
		return new BulkUploadCheckResponse();
	}

	/**
	 * Create an instance of {@link UploadCheckResponse }
	 * 
	 */
	public UploadCheckResponse createUploadCheckResponse() {
		return new UploadCheckResponse();
	}

	/**
	 * Create an instance of {@link GetCustomerOrders }
	 * 
	 */
	public GetCustomerOrders createGetCustomerOrders() {
		return new GetCustomerOrders();
	}

	/**
	 * Create an instance of {@link GetCustomerOrdersResponse }
	 * 
	 */
	public GetCustomerOrdersResponse createGetCustomerOrdersResponse() {
		return new GetCustomerOrdersResponse();
	}

	/**
	 * Create an instance of {@link CustomerOrders }
	 * 
	 */
	public CustomerOrders createCustomerOrders() {
		return new CustomerOrders();
	}

	/**
	 * Create an instance of {@link UpdateOrders }
	 * 
	 */
	public UpdateOrders createUpdateOrders() {
		return new UpdateOrders();
	}

	/**
	 * Create an instance of {@link ArrayOfOrderUpdateItem }
	 * 
	 */
	public ArrayOfOrderUpdateItem createArrayOfOrderUpdateItem() {
		return new ArrayOfOrderUpdateItem();
	}

	/**
	 * Create an instance of {@link UpdateOrdersResponse }
	 * 
	 */
	public UpdateOrdersResponse createUpdateOrdersResponse() {
		return new UpdateOrdersResponse();
	}

	/**
	 * Create an instance of {@link UpdateOrdersResponse2 }
	 * 
	 */
	public UpdateOrdersResponse2 createUpdateOrdersResponse2() {
		return new UpdateOrdersResponse2();
	}

	/**
	 * Create an instance of {@link UpdateOrdersWithTracking }
	 * 
	 */
	public UpdateOrdersWithTracking createUpdateOrdersWithTracking() {
		return new UpdateOrdersWithTracking();
	}

	/**
	 * Create an instance of {@link ArrayOfOrderUpdateItemWithTracking }
	 * 
	 */
	public ArrayOfOrderUpdateItemWithTracking createArrayOfOrderUpdateItemWithTracking() {
		return new ArrayOfOrderUpdateItemWithTracking();
	}

	/**
	 * Create an instance of {@link UpdateOrdersWithTrackingResponse }
	 * 
	 */
	public UpdateOrdersWithTrackingResponse createUpdateOrdersWithTrackingResponse() {
		return new UpdateOrdersWithTrackingResponse();
	}

	/**
	 * Create an instance of {@link GetRetailerMarketplaces }
	 * 
	 */
	public GetRetailerMarketplaces createGetRetailerMarketplaces() {
		return new GetRetailerMarketplaces();
	}

	/**
	 * Create an instance of {@link GetRetailerMarketplacesResponse }
	 * 
	 */
	public GetRetailerMarketplacesResponse createGetRetailerMarketplacesResponse() {
		return new GetRetailerMarketplacesResponse();
	}

	/**
	 * Create an instance of {@link GetRetailerMarketplacesResponse2 }
	 * 
	 */
	public GetRetailerMarketplacesResponse2 createGetRetailerMarketplacesResponse2() {
		return new GetRetailerMarketplacesResponse2();
	}

	/**
	 * Create an instance of {@link GetRetailerPricingProfiles }
	 * 
	 */
	public GetRetailerPricingProfiles createGetRetailerPricingProfiles() {
		return new GetRetailerPricingProfiles();
	}

	/**
	 * Create an instance of {@link GetRetailerPricingProfilesResponse }
	 * 
	 */
	public GetRetailerPricingProfilesResponse createGetRetailerPricingProfilesResponse() {
		return new GetRetailerPricingProfilesResponse();
	}

	/**
	 * Create an instance of {@link GetRetailerPricingProfilesResponse2 }
	 * 
	 */
	public GetRetailerPricingProfilesResponse2 createGetRetailerPricingProfilesResponse2() {
		return new GetRetailerPricingProfilesResponse2();
	}

	/**
	 * Create an instance of {@link GetSettlementData }
	 * 
	 */
	public GetSettlementData createGetSettlementData() {
		return new GetSettlementData();
	}

	/**
	 * Create an instance of {@link GetSettlementDataResponse }
	 * 
	 */
	public GetSettlementDataResponse createGetSettlementDataResponse() {
		return new GetSettlementDataResponse();
	}

	/**
	 * Create an instance of {@link SettlementData }
	 * 
	 */
	public SettlementData createSettlementData() {
		return new SettlementData();
	}

	/**
	 * Create an instance of {@link PaginationObject }
	 * 
	 */
	public PaginationObject createPaginationObject() {
		return new PaginationObject();
	}

	/**
	 * Create an instance of {@link ArrayOfCustomerOrder }
	 * 
	 */
	public ArrayOfCustomerOrder createArrayOfCustomerOrder() {
		return new ArrayOfCustomerOrder();
	}

	/**
	 * Create an instance of {@link CustomerOrder }
	 * 
	 */
	public CustomerOrder createCustomerOrder() {
		return new CustomerOrder();
	}

	/**
	 * Create an instance of {@link OrderUpdateItem }
	 * 
	 */
	public OrderUpdateItem createOrderUpdateItem() {
		return new OrderUpdateItem();
	}

	/**
	 * Create an instance of {@link OrderUpdateItemWithTracking }
	 * 
	 */
	public OrderUpdateItemWithTracking createOrderUpdateItemWithTracking() {
		return new OrderUpdateItemWithTracking();
	}

	/**
	 * Create an instance of {@link ArrayOfRetailerMarketplace }
	 * 
	 */
	public ArrayOfRetailerMarketplace createArrayOfRetailerMarketplace() {
		return new ArrayOfRetailerMarketplace();
	}

	/**
	 * Create an instance of {@link RetailerMarketplace }
	 * 
	 */
	public RetailerMarketplace createRetailerMarketplace() {
		return new RetailerMarketplace();
	}

	/**
	 * Create an instance of {@link ArrayOfRetailerPricingProfile }
	 * 
	 */
	public ArrayOfRetailerPricingProfile createArrayOfRetailerPricingProfile() {
		return new ArrayOfRetailerPricingProfile();
	}

	/**
	 * Create an instance of {@link RetailerPricingProfile }
	 * 
	 */
	public RetailerPricingProfile createRetailerPricingProfile() {
		return new RetailerPricingProfile();
	}

	/**
	 * Create an instance of {@link ArrayOfSettlementDataItem }
	 * 
	 */
	public ArrayOfSettlementDataItem createArrayOfSettlementDataItem() {
		return new ArrayOfSettlementDataItem();
	}

	/**
	 * Create an instance of {@link SettlementDataItem }
	 * 
	 */
	public SettlementDataItem createSettlementDataItem() {
		return new SettlementDataItem();
	}

}
