/*
 * Copyright (C) 2017 Solenoid Augment Technologies Limited.
 * All rights reserved.
 */

// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.29 at 02:53:44 PM IST 
//

package com.solenoid.connector.sd.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for OrderUpdateItemWithTracking complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="OrderUpdateItemWithTracking"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="GoodsPurchasedId" type="{http://microsoft.com/wsdl/types/}guid"/&gt;
 *         &lt;element name="Courier" type="{https://my.sellerdynamics.com/}CourierType"/&gt;
 *         &lt;element name="OtherCourier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="TrackingNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="RecordVersion" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OrderUpdateItemWithTracking", propOrder = {
		"goodsPurchasedId", "courier", "otherCourier", "trackingNumber",
		"recordVersion" })
public class OrderUpdateItemWithTracking {

	@XmlElement(name = "GoodsPurchasedId", required = true)
	protected String goodsPurchasedId;
	@XmlElement(name = "Courier", required = true)
	@XmlSchemaType(name = "string")
	protected CourierType courier;
	@XmlElement(name = "OtherCourier")
	protected String otherCourier;
	@XmlElement(name = "TrackingNumber")
	protected String trackingNumber;
	@XmlElement(name = "RecordVersion")
	protected byte[] recordVersion;

	/**
	 * Gets the value of the goodsPurchasedId property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getGoodsPurchasedId() {
		return goodsPurchasedId;
	}

	/**
	 * Sets the value of the goodsPurchasedId property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setGoodsPurchasedId(String value) {
		this.goodsPurchasedId = value;
	}

	/**
	 * Gets the value of the courier property.
	 * 
	 * @return possible object is {@link CourierType }
	 * 
	 */
	public CourierType getCourier() {
		return courier;
	}

	/**
	 * Sets the value of the courier property.
	 * 
	 * @param value
	 *            allowed object is {@link CourierType }
	 * 
	 */
	public void setCourier(CourierType value) {
		this.courier = value;
	}

	/**
	 * Gets the value of the otherCourier property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getOtherCourier() {
		return otherCourier;
	}

	/**
	 * Sets the value of the otherCourier property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setOtherCourier(String value) {
		this.otherCourier = value;
	}

	/**
	 * Gets the value of the trackingNumber property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTrackingNumber() {
		return trackingNumber;
	}

	/**
	 * Sets the value of the trackingNumber property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTrackingNumber(String value) {
		this.trackingNumber = value;
	}

	/**
	 * Gets the value of the recordVersion property.
	 * 
	 * @return possible object is byte[]
	 */
	public byte[] getRecordVersion() {
		return recordVersion;
	}

	/**
	 * Sets the value of the recordVersion property.
	 * 
	 * @param value
	 *            allowed object is byte[]
	 */
	public void setRecordVersion(byte[] value) {
		this.recordVersion = value;
	}

}
