/*
 * Copyright (C) 2017 Solenoid Augment Technologies Limited.
 * All rights reserved.
 */

// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.29 at 02:53:44 PM IST 
//

package com.solenoid.connector.sd.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for PaginationObject complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="PaginationObject"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="PageSize" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="PageNumber" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="RecordsAffected" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PaginationObject", propOrder = { "pageSize", "pageNumber",
		"recordsAffected" })
public class PaginationObject {

	@XmlElement(name = "PageSize")
	protected int pageSize;
	@XmlElement(name = "PageNumber")
	protected int pageNumber;
	@XmlElement(name = "RecordsAffected")
	protected int recordsAffected;

	/**
	 * Gets the value of the pageSize property.
	 * 
	 */
	public int getPageSize() {
		return pageSize;
	}

	/**
	 * Sets the value of the pageSize property.
	 * 
	 */
	public void setPageSize(int value) {
		this.pageSize = value;
	}

	/**
	 * Gets the value of the pageNumber property.
	 * 
	 */
	public int getPageNumber() {
		return pageNumber;
	}

	/**
	 * Sets the value of the pageNumber property.
	 * 
	 */
	public void setPageNumber(int value) {
		this.pageNumber = value;
	}

	/**
	 * Gets the value of the recordsAffected property.
	 * 
	 */
	public int getRecordsAffected() {
		return recordsAffected;
	}

	/**
	 * Sets the value of the recordsAffected property.
	 * 
	 */
	public void setRecordsAffected(int value) {
		this.recordsAffected = value;
	}

}
