/*
 * Copyright (C) 2017 Solenoid Augment Technologies Limited.
 * All rights reserved.
 */

// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.29 at 02:53:44 PM IST 
//

package com.solenoid.connector.sd.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for RetailerMarketplace complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="RetailerMarketplace"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="RetailerMarketplaceId" type="{http://microsoft.com/wsdl/types/}guid"/&gt;
 *         &lt;element name="MarketplaceName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CurrencyCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RetailerMarketplace", propOrder = { "retailerMarketplaceId",
		"marketplaceName", "currencyCode" })
public class RetailerMarketplace {

	@XmlElement(name = "RetailerMarketplaceId", required = true)
	protected String retailerMarketplaceId;
	@XmlElement(name = "MarketplaceName")
	protected String marketplaceName;
	@XmlElement(name = "CurrencyCode")
	protected String currencyCode;

	/**
	 * Gets the value of the retailerMarketplaceId property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getRetailerMarketplaceId() {
		return retailerMarketplaceId;
	}

	/**
	 * Sets the value of the retailerMarketplaceId property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setRetailerMarketplaceId(String value) {
		this.retailerMarketplaceId = value;
	}

	/**
	 * Gets the value of the marketplaceName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getMarketplaceName() {
		return marketplaceName;
	}

	/**
	 * Sets the value of the marketplaceName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setMarketplaceName(String value) {
		this.marketplaceName = value;
	}

	/**
	 * Gets the value of the currencyCode property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCurrencyCode() {
		return currencyCode;
	}

	/**
	 * Sets the value of the currencyCode property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCurrencyCode(String value) {
		this.currencyCode = value;
	}

}
