/*
 * Copyright (C) 2017 Solenoid Augment Technologies Limited.
 * All rights reserved.
 */

// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.29 at 02:53:44 PM IST 
//

package com.solenoid.connector.sd.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for RetailerPricingProfile complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="RetailerPricingProfile"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="PricingProfileId" type="{http://microsoft.com/wsdl/types/}guid"/&gt;
 *         &lt;element name="PricingProfileName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RetailerPricingProfile", propOrder = { "pricingProfileId",
		"pricingProfileName" })
public class RetailerPricingProfile {

	@XmlElement(name = "PricingProfileId", required = true)
	protected String pricingProfileId;
	@XmlElement(name = "PricingProfileName")
	protected String pricingProfileName;

	/**
	 * Gets the value of the pricingProfileId property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPricingProfileId() {
		return pricingProfileId;
	}

	/**
	 * Sets the value of the pricingProfileId property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setPricingProfileId(String value) {
		this.pricingProfileId = value;
	}

	/**
	 * Gets the value of the pricingProfileName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPricingProfileName() {
		return pricingProfileName;
	}

	/**
	 * Sets the value of the pricingProfileName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setPricingProfileName(String value) {
		this.pricingProfileName = value;
	}

}
