/*
 * Copyright (C) 2017 Solenoid Augment Technologies Limited.
 * All rights reserved.
 */

// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.29 at 02:53:44 PM IST 
//

package com.solenoid.connector.sd.beans;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for SettlementDataItem complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="SettlementDataItem"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="PostedDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="TransactionType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="MarketplaceOrderID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="MarketplaceOrderItemID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ListingReference" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SKU" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Quantity" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="Amount" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Currency" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SettlementDataItem", propOrder = { "postedDate",
		"transactionType", "marketplaceOrderID", "marketplaceOrderItemID",
		"listingReference", "sku", "quantity", "amount", "type", "description",
		"currency" })
public class SettlementDataItem {

	@XmlElement(name = "PostedDate", required = true, nillable = true)
	@XmlSchemaType(name = "dateTime")
	protected XMLGregorianCalendar postedDate;
	@XmlElement(name = "TransactionType")
	protected String transactionType;
	@XmlElement(name = "MarketplaceOrderID")
	protected String marketplaceOrderID;
	@XmlElement(name = "MarketplaceOrderItemID")
	protected String marketplaceOrderItemID;
	@XmlElement(name = "ListingReference")
	protected String listingReference;
	@XmlElement(name = "SKU")
	protected String sku;
	@XmlElement(name = "Quantity", required = true, type = Integer.class, nillable = true)
	protected Integer quantity;
	@XmlElement(name = "Amount", required = true, nillable = true)
	protected BigDecimal amount;
	@XmlElement(name = "Type")
	protected String type;
	@XmlElement(name = "Description")
	protected String description;
	@XmlElement(name = "Currency")
	protected String currency;

	/**
	 * Gets the value of the postedDate property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public XMLGregorianCalendar getPostedDate() {
		return postedDate;
	}

	/**
	 * Sets the value of the postedDate property.
	 * 
	 * @param value
	 *            allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setPostedDate(XMLGregorianCalendar value) {
		this.postedDate = value;
	}

	/**
	 * Gets the value of the transactionType property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTransactionType() {
		return transactionType;
	}

	/**
	 * Sets the value of the transactionType property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTransactionType(String value) {
		this.transactionType = value;
	}

	/**
	 * Gets the value of the marketplaceOrderID property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getMarketplaceOrderID() {
		return marketplaceOrderID;
	}

	/**
	 * Sets the value of the marketplaceOrderID property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setMarketplaceOrderID(String value) {
		this.marketplaceOrderID = value;
	}

	/**
	 * Gets the value of the marketplaceOrderItemID property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getMarketplaceOrderItemID() {
		return marketplaceOrderItemID;
	}

	/**
	 * Sets the value of the marketplaceOrderItemID property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setMarketplaceOrderItemID(String value) {
		this.marketplaceOrderItemID = value;
	}

	/**
	 * Gets the value of the listingReference property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getListingReference() {
		return listingReference;
	}

	/**
	 * Sets the value of the listingReference property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setListingReference(String value) {
		this.listingReference = value;
	}

	/**
	 * Gets the value of the sku property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSKU() {
		return sku;
	}

	/**
	 * Sets the value of the sku property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSKU(String value) {
		this.sku = value;
	}

	/**
	 * Gets the value of the quantity property.
	 * 
	 * @return possible object is {@link Integer }
	 * 
	 */
	public Integer getQuantity() {
		return quantity;
	}

	/**
	 * Sets the value of the quantity property.
	 * 
	 * @param value
	 *            allowed object is {@link Integer }
	 * 
	 */
	public void setQuantity(Integer value) {
		this.quantity = value;
	}

	/**
	 * Gets the value of the amount property.
	 * 
	 * @return possible object is {@link BigDecimal }
	 * 
	 */
	public BigDecimal getAmount() {
		return amount;
	}

	/**
	 * Sets the value of the amount property.
	 * 
	 * @param value
	 *            allowed object is {@link BigDecimal }
	 * 
	 */
	public void setAmount(BigDecimal value) {
		this.amount = value;
	}

	/**
	 * Gets the value of the type property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getType() {
		return type;
	}

	/**
	 * Sets the value of the type property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setType(String value) {
		this.type = value;
	}

	/**
	 * Gets the value of the description property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * Sets the value of the description property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDescription(String value) {
		this.description = value;
	}

	/**
	 * Gets the value of the currency property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCurrency() {
		return currency;
	}

	/**
	 * Sets the value of the currency property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCurrency(String value) {
		this.currency = value;
	}

}
