/*
 * Copyright (C) 2017 Solenoid Augment Technologies Limited.
 * All rights reserved.
 */

// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.29 at 02:53:44 PM IST 
//

package com.solenoid.connector.sd.beans;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for StatusType.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name="StatusType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="NotSet"/&gt;
 *     &lt;enumeration value="Success"/&gt;
 *     &lt;enumeration value="Error"/&gt;
 *     &lt;enumeration value="NoSupplier"/&gt;
 *     &lt;enumeration value="NoRetailerMarketplace"/&gt;
 *     &lt;enumeration value="MoreThanOneRetailerMarketplace"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "StatusType")
@XmlEnum
public enum StatusType {

	@XmlEnumValue("NotSet")
	NOT_SET("NotSet"), @XmlEnumValue("Success")
	SUCCESS("Success"), @XmlEnumValue("Error")
	ERROR("Error"), @XmlEnumValue("NoSupplier")
	NO_SUPPLIER("NoSupplier"), @XmlEnumValue("NoRetailerMarketplace")
	NO_RETAILER_MARKETPLACE("NoRetailerMarketplace"), @XmlEnumValue("MoreThanOneRetailerMarketplace")
	MORE_THAN_ONE_RETAILER_MARKETPLACE("MoreThanOneRetailerMarketplace");
	private final String value;

	StatusType(String v) {
		value = v;
	}

	public String value() {
		return value;
	}

	public static StatusType fromValue(String v) {
		for (StatusType c : StatusType.values()) {
			if (c.value.equals(v)) {
				return c;
			}
		}
		throw new IllegalArgumentException(v);
	}

}
